### ISSUE TITLE
Implement Quality Metrics 

### ISSUE THREAD

**Issue by lu-zero** [livepeer/TranscodingVerification#1]
- [x] Per-plane PSNR (Candidates: `PSNR-HVS-M`, `PSNR-HVS`)
- [x] MS-SSIM

**Comment by lu-zero** [comment]
Currently there is a plain `psnr` acting as placeholder.

**Comment by j0sh** [comment]
Since PSNR and MS-SSIM are per-frame metrics, how should we handle the transcoded output being at a different video framerate or audio sampling rate from the source input? I can imagine this leading to spurious false negatives around scene-cuts and such. Do we need to be very careful to match the interpolation that the encoder does?

**Comment by lu-zero** [comment]
The encoders do not do any kind of interpolation, any frame manipulation must happen outside the actual encoding process.

We cannot validate if we do not have access to the input and the output frames correctly.

**Comment by j0sh** [comment]
Suppose it is the libavfilter fps filter that is doing the interpolation. Does that mean we need to invoke the same filter (or ensure the frame-selection algorithm matches *exactly*) in order to get reliable results?

**Comment by luctrudeau** [comment]
To complement @lu-zero answer, all preprocessing tasks (resolution, frame rate...) must occur prior to the encoding.

If multiple frame rates or resolutions are required, this implies that multiple versions of the source must be made available to verifying nodes. 

If this is too expensive, please inform us, and we will consider alternatives.

**Comment by j0sh** [comment]
> this implies that multiple versions of the source must be made available

Do you mean each transcoding **result** must be made available, rather than the source input? If so, then yes that is a reasonable assumption, given the (single) source input is also made available.

We can make the trade off and have strict preprocessing rules. My thinking is that the behavior for each preprocessing step should to be fully spec'd out. Basically, we want to avoid the situation where an implementation quirk becomes the canonical behavior, or a subtle change to a library breaks deployed verification systems (eg, discrepancies between the avfilter versions used by a set of nodes). This will also have to become a coordination point within the higher-level job and verification protocol if/when we have to make adjustments to the preprocessing scheme.

**Comment by lu-zero** [comment]
(we forgot to update the issue after our meeting, updating now)

> Do you mean each transcoding result must be made available, rather than the source input? If so, then yes that is a reasonable assumption, given the (single) source input is also made available.

Exactly, the process works on the input and reconstructed frames, any filtering that happens before the frame data hits the encoder has to be faithfully replayed on validation.
