### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by lu-zero** [livepeer/TranscodingVerification#5]
- [x] [meson](http://mesonbuild.com/) simple build system
- [x] pkg-config file
- [ ] make sure the library can be imported in Go

**Comment by j0sh** [comment]
golang likes pkg-config and static libs :+1:

We will also likely be vendoring the code, if that helps.

**Comment by lu-zero** [comment]
I made the build system produce a pkg-config file and produce a static library by default.

**Comment by j0sh** [comment]
Looks good, I was able to build it with meson / ninja on my end. How do we generate the pkg-config file?

Was also able to build the test using a plain gcc command, ` gcc -Iinclude src/*.c test/metrics.c ` . Since we probably don't want to require our users to install extra build-time tools just for this, I can add a simple Makefile just for golang.

**Comment by lu-zero** [comment]
The install target generates the pkg-config file.

**Comment by lu-zero** [comment]
I'll try to keep the code buildable by that simple invocation, you might have to add `-DFIXED_POINT` in the future once the fixed-point math support lands.
